version: '3.8'

services:
  skillsync-frontend:
    image: skillsyncadmin.azurecr.io/skillsync-frontend:latest
    container_name: skillsync-frontend
    # No 'ports' mapped to the VM. 
    # NPM handles the public traffic from port 80/443.
    expose:
      - "80"
    networks:
      - skillsync-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

networks:
  skillsync-proxy:
    external: true