# ==========================================
# APPLICATION
# ==========================================
spring.application.name=notification-service
server.port=8086

# CONFIG SERVER INTEGRATION
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://config-server:8888

# LOGGING
logging.level.root=INFO
logging.file.name=logs/notification-service.log
