# ==========================================
# APPLICATION
# ==========================================
spring.application.name=auth-service
server.port=8081

# CONFIG SERVER INTEGRATION
# Fetch centralized properties from the Config Server
spring.cloud.config.enabled=true
spring.config.import=configserver:http://config-server:8888

# LOGGING
logging.level.root=INFO
logging.file.name=logs/auth-service.log
