# ==========================================
# MESSAGING SERVICE
# ==========================================
spring.application.name=messaging-service
server.port=8090

# CONFIG SERVER INTEGRATION
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://config-server:8888

# LOGGING
logging.level.root=INFO
logging.file.name=logs/messaging-service.log

# Force Rebuild: 20260414-1755

# Trigger pipeline forcely
