sonar.projectKey=review-service
sonar.projectName=review-service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.token=sqa_1edaaa4805d6b2f3447a0845bdb55fd59306398a
