{
 "title": "Log Explorer",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "auth-service, user-service, skill-service, session-service, mentor-service, group-service, review-service, notification-service, payment-gateway, messaging-service, api-gateway, .*"
   }
  ]
 },
 "panels": [
  {
   "title": "Dynamic Service Filter",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Global Error Logs",
   "type": "logs",
   "gridPos": { "x": 12, "y": 0, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{service=~\"$service\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "RabbitMQ Pub/Sub",
   "type": "logs",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{service=~\"$service\"} |= \"Publishing\" or {service=~\"$service\"} |= \"Consuming\""
    }
   ]
  },
  {
   "title": "Feign Errors",
   "type": "logs",
   "gridPos": { "x": 12, "y": 8, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{service=~\"$service\"} |= \"FeignException\""
    }
   ]
  }
 ]
}