apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Zipkin
    type: zipkin
    uid: zipkin-skillsync
    access: proxy
    url: http://zipkin-server:9411
    editable: false

  - name: Loki
    type: loki
    uid: loki-skillsync
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: zipkin-skillsync
          matcherRegex: "traceId=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
