# ==========================================
# APPLICATION
# ==========================================
spring.application.name=review-service
server.port=8088

# CONFIG SERVER INTEGRATION
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://config-server:8888

# LOGGING
logging.level.root=INFO
logging.file.name=logs/review-service.log

# Force Rebuild: 20260414-1755
